// ethquad: four-MAC cluster — 4 identical ethmac
// instances behind suffixed ports; shared WISHBONE
// clock/reset. F9.6 substrate (GENERATED by
// factory/build_tranche_b1.py).
module ethquad (
  wb_clk_i,
  wb_rst_i,
  wb_dat_i_0,
  wb_dat_o_0,
  wb_err_o_0,
  wb_adr_i_0,
  wb_sel_i_0,
  wb_we_i_0,
  wb_cyc_i_0,
  wb_stb_i_0,
  wb_ack_o_0,
  m_wb_adr_o_0,
  m_wb_sel_o_0,
  m_wb_we_o_0,
  m_wb_dat_i_0,
  m_wb_dat_o_0,
  m_wb_cyc_o_0,
  m_wb_stb_o_0,
  m_wb_ack_i_0,
  m_wb_err_i_0,
  m_wb_cti_o_0,
  m_wb_bte_o_0,
  mtx_clk_pad_i_0,
  mtxd_pad_o_0,
  mtxen_pad_o_0,
  mtxerr_pad_o_0,
  mrx_clk_pad_i_0,
  mrxd_pad_i_0,
  mrxdv_pad_i_0,
  mrxerr_pad_i_0,
  mcoll_pad_i_0,
  mcrs_pad_i_0,
  md_pad_i_0,
  mdc_pad_o_0,
  md_pad_o_0,
  md_padoe_o_0,
  int_o_0,
  wb_dat_i_1,
  wb_dat_o_1,
  wb_err_o_1,
  wb_adr_i_1,
  wb_sel_i_1,
  wb_we_i_1,
  wb_cyc_i_1,
  wb_stb_i_1,
  wb_ack_o_1,
  m_wb_adr_o_1,
  m_wb_sel_o_1,
  m_wb_we_o_1,
  m_wb_dat_i_1,
  m_wb_dat_o_1,
  m_wb_cyc_o_1,
  m_wb_stb_o_1,
  m_wb_ack_i_1,
  m_wb_err_i_1,
  m_wb_cti_o_1,
  m_wb_bte_o_1,
  mtx_clk_pad_i_1,
  mtxd_pad_o_1,
  mtxen_pad_o_1,
  mtxerr_pad_o_1,
  mrx_clk_pad_i_1,
  mrxd_pad_i_1,
  mrxdv_pad_i_1,
  mrxerr_pad_i_1,
  mcoll_pad_i_1,
  mcrs_pad_i_1,
  md_pad_i_1,
  mdc_pad_o_1,
  md_pad_o_1,
  md_padoe_o_1,
  int_o_1,
  wb_dat_i_2,
  wb_dat_o_2,
  wb_err_o_2,
  wb_adr_i_2,
  wb_sel_i_2,
  wb_we_i_2,
  wb_cyc_i_2,
  wb_stb_i_2,
  wb_ack_o_2,
  m_wb_adr_o_2,
  m_wb_sel_o_2,
  m_wb_we_o_2,
  m_wb_dat_i_2,
  m_wb_dat_o_2,
  m_wb_cyc_o_2,
  m_wb_stb_o_2,
  m_wb_ack_i_2,
  m_wb_err_i_2,
  m_wb_cti_o_2,
  m_wb_bte_o_2,
  mtx_clk_pad_i_2,
  mtxd_pad_o_2,
  mtxen_pad_o_2,
  mtxerr_pad_o_2,
  mrx_clk_pad_i_2,
  mrxd_pad_i_2,
  mrxdv_pad_i_2,
  mrxerr_pad_i_2,
  mcoll_pad_i_2,
  mcrs_pad_i_2,
  md_pad_i_2,
  mdc_pad_o_2,
  md_pad_o_2,
  md_padoe_o_2,
  int_o_2,
  wb_dat_i_3,
  wb_dat_o_3,
  wb_err_o_3,
  wb_adr_i_3,
  wb_sel_i_3,
  wb_we_i_3,
  wb_cyc_i_3,
  wb_stb_i_3,
  wb_ack_o_3,
  m_wb_adr_o_3,
  m_wb_sel_o_3,
  m_wb_we_o_3,
  m_wb_dat_i_3,
  m_wb_dat_o_3,
  m_wb_cyc_o_3,
  m_wb_stb_o_3,
  m_wb_ack_i_3,
  m_wb_err_i_3,
  m_wb_cti_o_3,
  m_wb_bte_o_3,
  mtx_clk_pad_i_3,
  mtxd_pad_o_3,
  mtxen_pad_o_3,
  mtxerr_pad_o_3,
  mrx_clk_pad_i_3,
  mrxd_pad_i_3,
  mrxdv_pad_i_3,
  mrxerr_pad_i_3,
  mcoll_pad_i_3,
  mcrs_pad_i_3,
  md_pad_i_3,
  mdc_pad_o_3,
  md_pad_o_3,
  md_padoe_o_3,
  int_o_3
);
input  wb_clk_i;
input  wb_rst_i;
input  [31:0] wb_dat_i_0;
output [31:0] wb_dat_o_0;
output wb_err_o_0;
input  [11:2] wb_adr_i_0;
input  [3:0] wb_sel_i_0;
input  wb_we_i_0;
input  wb_cyc_i_0;
input  wb_stb_i_0;
output wb_ack_o_0;
output [31:0] m_wb_adr_o_0;
output [3:0] m_wb_sel_o_0;
output m_wb_we_o_0;
input  [31:0] m_wb_dat_i_0;
output [31:0] m_wb_dat_o_0;
output m_wb_cyc_o_0;
output m_wb_stb_o_0;
input  m_wb_ack_i_0;
input  m_wb_err_i_0;
output [2:0] m_wb_cti_o_0;
output [1:0] m_wb_bte_o_0;
input  mtx_clk_pad_i_0;
output [3:0] mtxd_pad_o_0;
output mtxen_pad_o_0;
output mtxerr_pad_o_0;
input  mrx_clk_pad_i_0;
input  [3:0] mrxd_pad_i_0;
input  mrxdv_pad_i_0;
input  mrxerr_pad_i_0;
input  mcoll_pad_i_0;
input  mcrs_pad_i_0;
input  md_pad_i_0;
output mdc_pad_o_0;
output md_pad_o_0;
output md_padoe_o_0;
output int_o_0;
input  [31:0] wb_dat_i_1;
output [31:0] wb_dat_o_1;
output wb_err_o_1;
input  [11:2] wb_adr_i_1;
input  [3:0] wb_sel_i_1;
input  wb_we_i_1;
input  wb_cyc_i_1;
input  wb_stb_i_1;
output wb_ack_o_1;
output [31:0] m_wb_adr_o_1;
output [3:0] m_wb_sel_o_1;
output m_wb_we_o_1;
input  [31:0] m_wb_dat_i_1;
output [31:0] m_wb_dat_o_1;
output m_wb_cyc_o_1;
output m_wb_stb_o_1;
input  m_wb_ack_i_1;
input  m_wb_err_i_1;
output [2:0] m_wb_cti_o_1;
output [1:0] m_wb_bte_o_1;
input  mtx_clk_pad_i_1;
output [3:0] mtxd_pad_o_1;
output mtxen_pad_o_1;
output mtxerr_pad_o_1;
input  mrx_clk_pad_i_1;
input  [3:0] mrxd_pad_i_1;
input  mrxdv_pad_i_1;
input  mrxerr_pad_i_1;
input  mcoll_pad_i_1;
input  mcrs_pad_i_1;
input  md_pad_i_1;
output mdc_pad_o_1;
output md_pad_o_1;
output md_padoe_o_1;
output int_o_1;
input  [31:0] wb_dat_i_2;
output [31:0] wb_dat_o_2;
output wb_err_o_2;
input  [11:2] wb_adr_i_2;
input  [3:0] wb_sel_i_2;
input  wb_we_i_2;
input  wb_cyc_i_2;
input  wb_stb_i_2;
output wb_ack_o_2;
output [31:0] m_wb_adr_o_2;
output [3:0] m_wb_sel_o_2;
output m_wb_we_o_2;
input  [31:0] m_wb_dat_i_2;
output [31:0] m_wb_dat_o_2;
output m_wb_cyc_o_2;
output m_wb_stb_o_2;
input  m_wb_ack_i_2;
input  m_wb_err_i_2;
output [2:0] m_wb_cti_o_2;
output [1:0] m_wb_bte_o_2;
input  mtx_clk_pad_i_2;
output [3:0] mtxd_pad_o_2;
output mtxen_pad_o_2;
output mtxerr_pad_o_2;
input  mrx_clk_pad_i_2;
input  [3:0] mrxd_pad_i_2;
input  mrxdv_pad_i_2;
input  mrxerr_pad_i_2;
input  mcoll_pad_i_2;
input  mcrs_pad_i_2;
input  md_pad_i_2;
output mdc_pad_o_2;
output md_pad_o_2;
output md_padoe_o_2;
output int_o_2;
input  [31:0] wb_dat_i_3;
output [31:0] wb_dat_o_3;
output wb_err_o_3;
input  [11:2] wb_adr_i_3;
input  [3:0] wb_sel_i_3;
input  wb_we_i_3;
input  wb_cyc_i_3;
input  wb_stb_i_3;
output wb_ack_o_3;
output [31:0] m_wb_adr_o_3;
output [3:0] m_wb_sel_o_3;
output m_wb_we_o_3;
input  [31:0] m_wb_dat_i_3;
output [31:0] m_wb_dat_o_3;
output m_wb_cyc_o_3;
output m_wb_stb_o_3;
input  m_wb_ack_i_3;
input  m_wb_err_i_3;
output [2:0] m_wb_cti_o_3;
output [1:0] m_wb_bte_o_3;
input  mtx_clk_pad_i_3;
output [3:0] mtxd_pad_o_3;
output mtxen_pad_o_3;
output mtxerr_pad_o_3;
input  mrx_clk_pad_i_3;
input  [3:0] mrxd_pad_i_3;
input  mrxdv_pad_i_3;
input  mrxerr_pad_i_3;
input  mcoll_pad_i_3;
input  mcrs_pad_i_3;
input  md_pad_i_3;
output mdc_pad_o_3;
output md_pad_o_3;
output md_padoe_o_3;
output int_o_3;
  ethmac u_mac0 (
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_dat_i(wb_dat_i_0),
    .wb_dat_o(wb_dat_o_0),
    .wb_err_o(wb_err_o_0),
    .wb_adr_i(wb_adr_i_0),
    .wb_sel_i(wb_sel_i_0),
    .wb_we_i(wb_we_i_0),
    .wb_cyc_i(wb_cyc_i_0),
    .wb_stb_i(wb_stb_i_0),
    .wb_ack_o(wb_ack_o_0),
    .m_wb_adr_o(m_wb_adr_o_0),
    .m_wb_sel_o(m_wb_sel_o_0),
    .m_wb_we_o(m_wb_we_o_0),
    .m_wb_dat_i(m_wb_dat_i_0),
    .m_wb_dat_o(m_wb_dat_o_0),
    .m_wb_cyc_o(m_wb_cyc_o_0),
    .m_wb_stb_o(m_wb_stb_o_0),
    .m_wb_ack_i(m_wb_ack_i_0),
    .m_wb_err_i(m_wb_err_i_0),
    .m_wb_cti_o(m_wb_cti_o_0),
    .m_wb_bte_o(m_wb_bte_o_0),
    .mtx_clk_pad_i(mtx_clk_pad_i_0),
    .mtxd_pad_o(mtxd_pad_o_0),
    .mtxen_pad_o(mtxen_pad_o_0),
    .mtxerr_pad_o(mtxerr_pad_o_0),
    .mrx_clk_pad_i(mrx_clk_pad_i_0),
    .mrxd_pad_i(mrxd_pad_i_0),
    .mrxdv_pad_i(mrxdv_pad_i_0),
    .mrxerr_pad_i(mrxerr_pad_i_0),
    .mcoll_pad_i(mcoll_pad_i_0),
    .mcrs_pad_i(mcrs_pad_i_0),
    .md_pad_i(md_pad_i_0),
    .mdc_pad_o(mdc_pad_o_0),
    .md_pad_o(md_pad_o_0),
    .md_padoe_o(md_padoe_o_0),
    .int_o(int_o_0)
  );
  ethmac u_mac1 (
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_dat_i(wb_dat_i_1),
    .wb_dat_o(wb_dat_o_1),
    .wb_err_o(wb_err_o_1),
    .wb_adr_i(wb_adr_i_1),
    .wb_sel_i(wb_sel_i_1),
    .wb_we_i(wb_we_i_1),
    .wb_cyc_i(wb_cyc_i_1),
    .wb_stb_i(wb_stb_i_1),
    .wb_ack_o(wb_ack_o_1),
    .m_wb_adr_o(m_wb_adr_o_1),
    .m_wb_sel_o(m_wb_sel_o_1),
    .m_wb_we_o(m_wb_we_o_1),
    .m_wb_dat_i(m_wb_dat_i_1),
    .m_wb_dat_o(m_wb_dat_o_1),
    .m_wb_cyc_o(m_wb_cyc_o_1),
    .m_wb_stb_o(m_wb_stb_o_1),
    .m_wb_ack_i(m_wb_ack_i_1),
    .m_wb_err_i(m_wb_err_i_1),
    .m_wb_cti_o(m_wb_cti_o_1),
    .m_wb_bte_o(m_wb_bte_o_1),
    .mtx_clk_pad_i(mtx_clk_pad_i_1),
    .mtxd_pad_o(mtxd_pad_o_1),
    .mtxen_pad_o(mtxen_pad_o_1),
    .mtxerr_pad_o(mtxerr_pad_o_1),
    .mrx_clk_pad_i(mrx_clk_pad_i_1),
    .mrxd_pad_i(mrxd_pad_i_1),
    .mrxdv_pad_i(mrxdv_pad_i_1),
    .mrxerr_pad_i(mrxerr_pad_i_1),
    .mcoll_pad_i(mcoll_pad_i_1),
    .mcrs_pad_i(mcrs_pad_i_1),
    .md_pad_i(md_pad_i_1),
    .mdc_pad_o(mdc_pad_o_1),
    .md_pad_o(md_pad_o_1),
    .md_padoe_o(md_padoe_o_1),
    .int_o(int_o_1)
  );
  ethmac u_mac2 (
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_dat_i(wb_dat_i_2),
    .wb_dat_o(wb_dat_o_2),
    .wb_err_o(wb_err_o_2),
    .wb_adr_i(wb_adr_i_2),
    .wb_sel_i(wb_sel_i_2),
    .wb_we_i(wb_we_i_2),
    .wb_cyc_i(wb_cyc_i_2),
    .wb_stb_i(wb_stb_i_2),
    .wb_ack_o(wb_ack_o_2),
    .m_wb_adr_o(m_wb_adr_o_2),
    .m_wb_sel_o(m_wb_sel_o_2),
    .m_wb_we_o(m_wb_we_o_2),
    .m_wb_dat_i(m_wb_dat_i_2),
    .m_wb_dat_o(m_wb_dat_o_2),
    .m_wb_cyc_o(m_wb_cyc_o_2),
    .m_wb_stb_o(m_wb_stb_o_2),
    .m_wb_ack_i(m_wb_ack_i_2),
    .m_wb_err_i(m_wb_err_i_2),
    .m_wb_cti_o(m_wb_cti_o_2),
    .m_wb_bte_o(m_wb_bte_o_2),
    .mtx_clk_pad_i(mtx_clk_pad_i_2),
    .mtxd_pad_o(mtxd_pad_o_2),
    .mtxen_pad_o(mtxen_pad_o_2),
    .mtxerr_pad_o(mtxerr_pad_o_2),
    .mrx_clk_pad_i(mrx_clk_pad_i_2),
    .mrxd_pad_i(mrxd_pad_i_2),
    .mrxdv_pad_i(mrxdv_pad_i_2),
    .mrxerr_pad_i(mrxerr_pad_i_2),
    .mcoll_pad_i(mcoll_pad_i_2),
    .mcrs_pad_i(mcrs_pad_i_2),
    .md_pad_i(md_pad_i_2),
    .mdc_pad_o(mdc_pad_o_2),
    .md_pad_o(md_pad_o_2),
    .md_padoe_o(md_padoe_o_2),
    .int_o(int_o_2)
  );
  ethmac u_mac3 (
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_dat_i(wb_dat_i_3),
    .wb_dat_o(wb_dat_o_3),
    .wb_err_o(wb_err_o_3),
    .wb_adr_i(wb_adr_i_3),
    .wb_sel_i(wb_sel_i_3),
    .wb_we_i(wb_we_i_3),
    .wb_cyc_i(wb_cyc_i_3),
    .wb_stb_i(wb_stb_i_3),
    .wb_ack_o(wb_ack_o_3),
    .m_wb_adr_o(m_wb_adr_o_3),
    .m_wb_sel_o(m_wb_sel_o_3),
    .m_wb_we_o(m_wb_we_o_3),
    .m_wb_dat_i(m_wb_dat_i_3),
    .m_wb_dat_o(m_wb_dat_o_3),
    .m_wb_cyc_o(m_wb_cyc_o_3),
    .m_wb_stb_o(m_wb_stb_o_3),
    .m_wb_ack_i(m_wb_ack_i_3),
    .m_wb_err_i(m_wb_err_i_3),
    .m_wb_cti_o(m_wb_cti_o_3),
    .m_wb_bte_o(m_wb_bte_o_3),
    .mtx_clk_pad_i(mtx_clk_pad_i_3),
    .mtxd_pad_o(mtxd_pad_o_3),
    .mtxen_pad_o(mtxen_pad_o_3),
    .mtxerr_pad_o(mtxerr_pad_o_3),
    .mrx_clk_pad_i(mrx_clk_pad_i_3),
    .mrxd_pad_i(mrxd_pad_i_3),
    .mrxdv_pad_i(mrxdv_pad_i_3),
    .mrxerr_pad_i(mrxerr_pad_i_3),
    .mcoll_pad_i(mcoll_pad_i_3),
    .mcrs_pad_i(mcrs_pad_i_3),
    .md_pad_i(md_pad_i_3),
    .mdc_pad_o(mdc_pad_o_3),
    .md_pad_o(md_pad_o_3),
    .md_padoe_o(md_padoe_o_3),
    .int_o(int_o_3)
  );
endmodule
