// mpb_soc1: macro-placement-benchmark SoC — 16 fakeram7_256x32
// scratchpad banks, address-decoded single port, registered read mux,
// xor-fold pipeline across banks (cross-macro timing paths).
// GENERATED by factory/f4/gen_mpb_soc.py — regenerate, do not edit.
module mpb_soc1 (
    input                  clk,
    input                  rst_n,
    input                  req_valid,
    input                  req_we,
    input      [12-1:0]  req_addr,   // {bank[4-1:0], word[7:0]}
    input      [31:0]      req_wdata,
    output reg [31:0]      resp_rdata,
    output reg             resp_valid,
    output reg [31:0]      fold
);
    wire [4-1:0] bank_sel = req_addr[12-1:8];
    wire [7:0]      word     = req_addr[7:0];
    wire [31:0]     rd       [0:16-1];
    reg  [4-1:0] bank_q;

    genvar gi;
    generate
        for (gi = 0; gi < 16; gi = gi + 1) begin : g_bank
            wire ce = req_valid && (bank_sel == gi[4-1:0]);
            fakeram7_256x32 u_mem (
                .clk     (clk),
                .ce_in   (ce),
                .we_in   (ce && req_we),
                .addr_in (word),
                .wd_in   (req_wdata),
                .rd_out  (rd[gi])
            );
        end
    endgenerate

    // Cross-macro pressure: combinational xor-fold of every bank's
    // read port (single registered sink; no last-write-wins wart).
    integer i;
    reg [31:0] acc;
    always @* begin
        acc = 32'd0;
        for (i = 0; i < 16; i = i + 1)
            acc = acc ^ rd[i];
    end

    always @(posedge clk) begin
        if (!rst_n) begin
            resp_valid <= 1'b0;
            resp_rdata <= 32'd0;
            bank_q     <= {4{1'b0}};
            fold       <= 32'd0;
        end else begin
            bank_q     <= bank_sel;
            resp_valid <= req_valid && !req_we;
            resp_rdata <= rd[bank_q];
            fold       <= fold ^ rd[bank_q] ^ acc;
        end
    end
endmodule
